### ISSUE TITLE
Which widget should be scheduled to rebuild upon state change?

### ISSUE THREAD

**Issue by AntonEriksson978** [lukehutch/flutter_reactive_value#1]
From the README.md:

> Now whenever counter.value changes (here using counter.value++ in the onPressed handler), the enclosing widget (here HomeView) will be scheduled for rebuilding.
> 
> (The only place you're not allowed to update counter.value is the build method of a widget, since state changes are disallowed in build methods.)
> 
> That's all there is to it!

"Upon reading this in your documentation, I am curious: wouldn't we only want the Text widget to rebuild instead of the enclosing widget (in this case, HomeView)?"

**Comment by lukehutch** [comment]
It's the widget that is the `BuildContext` passed into `reactiveValue` that is scheduled to be rebuilt. `BuildContext` is actually an `Element`, so technically it's the `Element`, not the `Widget`, that is rebuilt -- `Element` is the laid-out view of a widget. The scheduling happens via `Element.markMeedsBuild()`.

This may trigger other elements to be rebuilt too, especially if the size of the `Element` changes, since constraints are passed down the `Element` tree and sizes are passed back up. And of course it will trigger a render frame, which (I assume) will only redraw the area of the screen that was marked for rebuilding, but I'm not sure about that.

I should update the docs to make this clearer, sorry!

**Comment by lukehutch** [comment]
Sorry, I reread your question... The `Text` Widget optimally would be the only one rebuilt, yes. But it has no `BuildContext`, so there's no way to get a reference to it.

In general you should be breaking large coplex widget trees down into separate widgets, for readability if nothing else, so usually widget trees go only a few layers deep below a `BuildContext`, and the re-layout should not be horribly wasteful.

**Comment by AntonEriksson978** [comment]
The [Builder](https://api.flutter.dev/flutter/widgets/Builder-class.html) widget could provide the parents `BuildContext` exactly where and when you need it.

**Comment by lukehutch** [comment]
Correct, I forgot about that, you can introduce `BuildContext` anywhere you want in that way for efficiency. I don't think there will be significant performance differences most of the time, because rebuilding is fairly lightweight once the `Element` tree is built. Also it's good style to keep widgets small in terms of tree size.

I'll update the docs.

**Comment by lukehutch** [comment]
@AntonEriksson978 The docs are updated. Thanks for pointing this out, it is an important point!
