### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by zupat** [lukehutch/flutter_reactive_value#5]
Based on the code, a new listener is registered on every rebuild and removed when the callback runs. There's is a bug when the widget is rebuilt is triggered from another ValueNotifier.

## Explanation:
We have 2 ValueNotifiers: `age` and `username`
Profile widget is watching both thus resulting in 1 listener being registered for each ValueNotifier
`username` is modified causing ProfileWidget to rebuild, another listener is registered for each but the old listener for `age` is still registered. It will register an unlimited amount of listeners until its value has changed.

**Comment by lukehutch** [comment]
OK, I found a way to do this efficiently using `Expando`. `ReactiveValueNotifier` is now a subclass though, not an extension. Published in 2.0.0. Thanks for the report!

**Comment by alwerr** [comment]
Does its fixed now? No memory leaks?

**Comment by lukehutch** [comment]
@alwerr There should be no memory leaks now, correct. But it is hard to test this, because testing this requires the garbage collector to be triggered.

**Comment by alwerr** [comment]
Ok. thanks, great package, @lukehutch do you still use it?

**Comment by lukehutch** [comment]
I actually don't use it anymore, because I have much more complex needs for ValueNotifiers now, such as defining a ValueNotifier that reactively responds to changes in multiple other ValueNotifiers (allowing a reactive DAG of notifies to be built). Also I use my other package, Persistent ValueNotifier a lot, and that no nonger works together with ReacrltiveValueNotifier as of version 2.0. So at this point I have about 8 different subclasses of ValueNotifier built for different purposes, and I just use them with ValueListenableBuilder, or my own alternative to that class which I also built (but haven't published yet).

The simplest thing to use today in general is simply ValueNotifier with ValueListenableBuilder, since both are included in Flutter.

**Comment by alwerr** [comment]
Persistent ValueNotifier looks really helpful, so I guess I would use  ValueNotifier with ValueListenableBuilder too, are they working in stateless widget too? like in this package?

**Comment by lukehutch** [comment]
Yes, ValueListenableBuilder is a stateful widget that rebuilds when the ValueNotifier it is watching changes. It can be used inside any widget (including a stateless widget). It's very simple to use. And PersistentValueNotifier works perfectly with it.
